### ISSUE TITLE
name

### ISSUE THREAD

**Issue by alissan** [JeremyHi/CryptoSym#25]
hi,

cryptosim is our magnificent product.
may be you can change your project name.

https://www.google.com.tr/search?q=cryptosim&oq=cryptosim&aqs=chrome..69i57j69i60l3j0.1233j0j7&sourceid=chrome&ie=UTF-8

thanks.

**Comment by niclego** [comment]
Are you trying to steal our product? My dad is a lawyer.

**Comment by seanrose123** [comment]
Hey son, yeah I got about 100 mil to pimp into your testimony too.

**Comment by JeremyHi** [comment]
@alissan, we will resolve this matter shortly, thank you for brining this issue to our attention. Sorry about any confusion, hope to not cause any problems.

**Comment by j-woodlee** [comment]
No resolution necessary, welcome to America.

**Comment by alissan** [comment]
@JeremyHi, thanks you for your understanding. i like your approach.

**Comment by alissan** [comment]
@niclego :))
